import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ApplicationProvider from './providers/ApplicationProvider'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import PushNotificationLayout from './components/Shared/PushNotificationLayout';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Dyarko',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicationProvider>
          <PushNotificationLayout>
          {children}
          <ToastContainer />
          </PushNotificationLayout>
        </ApplicationProvider>
      </body>
    </html>
  )
}
