import "./globals.css";
import { Inter } from "next/font/google";
import ApplicationProvider from "./providers/ApplicationProvider";
import PushNotificationLayout from "./components/Shared/PushNotificationLayout";
import { getLocale, getMessages } from "next-intl/server";
import ClientProviders from "./providers/ClientProviders";
import React, { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dyarko",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: ReactNode;
  modal: ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ClientProviders locale={locale} messages={messages}>
          <ApplicationProvider>
            <PushNotificationLayout>
              {children}
              {modal}
            </PushNotificationLayout>
          </ApplicationProvider>
        </ClientProviders>
      </body>
    </html>
  );
}
